name: interactive_resume
description: "An interactive resume application using GenUI."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ">=3.9.2 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  genui: ^0.5.1
  genui_google_generative_ai: ^0.5.1
  json_schema_builder: ^0.1.3
  intl: ^0.20.2
  url_launcher: ^6.3.1
  logging: ^1.3.0
  gpt_markdown: ^1.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
